name: Auto Update Upcoming Games

on:
  schedule:
    # Run every day at 6 AM UTC (adjust timezone as needed)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-games:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run auto pull script
      env:
        THESPORTSDB_API_KEY: ${{ secrets.THESPORTSDB_API_KEY }}
        APISPORTS_API_KEY: ${{ secrets.APISPORTS_API_KEY }}
      run: |
        python scripts/auto_pull_upcoming.py --db data.sqlite --days-ahead 60 --verbose
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data.sqlite
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update: Pull latest upcoming games [skip ci]"
          git push
        fi
        
    - name: Upload log file
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: update-log
        path: auto_update.log
