name: Automated Model Retraining

on:
  schedule:
    # Run every 4 hours to check for completed matches
    - cron: '0 */4 * * *'
  workflow_dispatch:  # Allow manual triggering
  push:
    paths:
      - 'data.sqlite'  # Trigger when database is updated

jobs:
  check-and-retrain:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check for completed matches and retrain
      env:
        THESPORTSDB_API_KEY: ${{ secrets.THESPORTSDB_API_KEY }}
        APISPORTS_API_KEY: ${{ secrets.APISPORTS_API_KEY }}
      run: |
        echo "🔍 Checking for completed matches..."
        python scripts/detect_completed_matches.py
        
    - name: Update all games from TheSportsDB
      run: |
        echo "📅 Updating all games from TheSportsDB..."
        python scripts/enhanced_auto_update.py --db data.sqlite --verbose
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data.sqlite artifacts/ last_checkpoint.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update: Retrained models and updated games [skip ci]"
          git push
        fi
        
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: retraining-logs
        path: |
          model_training.log
          match_detection.log
          auto_update.log
