[server]
# Configure CORS for iframe security
enableCORS = false

# Browser security settings
runOnSave = false

# Performance optimizations
maxUploadSize = 200

# Disable unnecessary features
enableWebsocketCompression = false
maxRequestSize = 50

# Frame options to reduce iframe warnings
frameOptions = "SAMEORIGIN"

[browser]
# Disable unnecessary features to reduce console warnings
gatherUsageStats = false

# Additional browser security settings
serverHeadless = false
serverRunOnSave = false
serverEnableWebsocketCompression = false

[theme]
# Optimize default theme
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[logger]
# Reduce log verbosity
level = "warning"